"""Initial recording and project schema"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("is_supervisor", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject", name="uq_user_identity"),
    )
    op.create_table(
        "research_animal",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("code ~ '^[A-Za-z]{3}$'", name="ck_animal_code"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "project",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("length(name) > 0", name="ck_project_name"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recording_session",
        sa.Column("animal_id", sa.Uuid(), nullable=False),
        sa.Column("session_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("session_number BETWEEN 0 AND 999", name="ck_session_number"),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["research_animal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("animal_id", "session_number", name="uq_animal_session"),
    )
    op.create_table(
        "import_record",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("imported_by", sa.Uuid(), nullable=False),
        sa.Column("received_filename", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("contract_version", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("staging_key", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'", name="ck_import_hash"),
        sa.CheckConstraint(
            "status IN ('RECEIVED','VALIDATING','IMPORTING','SUCCEEDED','REJECTED','SKIPPED','FAILED')",
            name="ck_import_status",
        ),
        sa.ForeignKeyConstraint(
            ["imported_by"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", name="uq_import_project"),
    )
    op.create_index("ix_import_status_started", "import_record", ["status", "started_at"], unique=False)
    op.create_table(
        "membership",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('LAB_MEMBER', 'GUEST')", name="ck_membership_role"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    op.create_table(
        "source_file",
        sa.Column("import_record_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("original_file_name", sa.String(), nullable=False),
        sa.Column("save_file_name", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("contract_version", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "source_structure", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name="ck_source_hash"),
        sa.CheckConstraint("byte_size > 0", name="ck_source_size"),
        sa.ForeignKeyConstraint(
            ["import_record_id", "project_id"],
            ["import_record.id", "import_record.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", name="uq_source_project"),
        sa.UniqueConstraint("import_record_id"),
        sa.UniqueConstraint("sha256"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "neuron_recording",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("neuron_number", sa.BigInteger(), nullable=False),
        sa.Column("experiment_type_name", sa.String(), nullable=False),
        sa.Column("training_phase_name", sa.String(), nullable=False),
        sa.Column("brain_area_name", sa.String(), nullable=False),
        sa.Column("experiment_type", sa.BigInteger(), nullable=False),
        sa.Column("training_phase_number", sa.BigInteger(), nullable=False),
        sa.Column("brain_area_number", sa.BigInteger(), nullable=False),
        sa.Column("trial_count", sa.Integer(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("sample_interval_us", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("sample_count = 6001", name="ck_sample_count"),
        sa.CheckConstraint("sample_interval_us = 1000", name="ck_interval"),
        sa.CheckConstraint("trial_count > 0", name="ck_trial_count"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["recording_session.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id", "project_id"],
            ["source_file.id", "source_file.project_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("neuron_number"),
        sa.UniqueConstraint("source_file_id"),
    )
    op.create_index(op.f("ix_neuron_recording_project_id"), "neuron_recording", ["project_id"], unique=False)
    op.create_index(op.f("ix_neuron_recording_session_id"), "neuron_recording", ["session_id"], unique=False)
    op.create_table(
        "trial",
        sa.Column("recording_id", sa.Uuid(), nullable=False),
        sa.Column("trial_index", sa.Integer(), nullable=False),
        sa.Column("stimulus_position_name", sa.String(), nullable=False),
        sa.Column("second_stimulus_position_name", sa.String(), nullable=False),
        sa.Column("is_match_trial", sa.Boolean(), nullable=False),
        sa.Column("cue_sample_interval_length", sa.Double(), nullable=False),
        sa.Column("cue_reward_interval_length", sa.Double(), nullable=False),
        sa.CheckConstraint(
            "second_stimulus_position_name IN ('upper_left', 'upper_center', 'upper_right', 'middle_left', 'middle_center', 'middle_right', 'lower_left', 'lower_center', 'lower_right')",
            name="ck_second_position",
        ),
        sa.CheckConstraint(
            "stimulus_position_name IN ('upper_left', 'upper_center', 'upper_right', 'middle_left', 'middle_center', 'middle_right', 'lower_left', 'lower_center', 'lower_right')",
            name="ck_first_position",
        ),
        sa.CheckConstraint(
            "is_match_trial = (stimulus_position_name = second_stimulus_position_name)", name="ck_match"
        ),
        sa.CheckConstraint("trial_index >= 1", name="ck_trial_index"),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["neuron_recording.id"],
        ),
        sa.PrimaryKeyConstraint("recording_id", "trial_index"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trial")
    op.drop_index(op.f("ix_neuron_recording_session_id"), table_name="neuron_recording")
    op.drop_index(op.f("ix_neuron_recording_project_id"), table_name="neuron_recording")
    op.drop_table("neuron_recording")
    op.drop_table("source_file")
    op.drop_table("membership")
    op.drop_index("ix_import_status_started", table_name="import_record")
    op.drop_table("import_record")
    op.drop_table("recording_session")
    op.drop_table("project")
    op.drop_table("research_animal")
    op.drop_table("app_user")
    # ### end Alembic commands ###
